name: Build and deploy Python app to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: fastcloseai    # set this to your application's name
  PYTHON_VERSION: '3.11'             # set this to the Python version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Generate requirements.txt
        run: |
          echo "email-validator>=2.2.0" > requirements.txt
          echo "flask-login>=0.6.3" >> requirements.txt
          echo "flask>=3.1.0" >> requirements.txt
          echo "flask-sqlalchemy>=3.1.1" >> requirements.txt
          echo "gunicorn>=23.0.0" >> requirements.txt
          echo "psycopg2-binary>=2.9.10" >> requirements.txt
          echo "trafilatura>=2.0.0" >> requirements.txt
          echo "werkzeug>=3.1.3" >> requirements.txt
          echo "wfastcgi>=3.0.0" >> requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install gunicorn

      - name: Create deployment package
        run: zip -r deploy.zip .

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: deploy.zip

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip deploy.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZUREWEBAPP_PUBLISHPROFILE }}