name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install email-validator==2.2.0 flask-login==0.6.3 flask==3.1.0 flask-sqlalchemy==3.1.1 gunicorn==23.0.0 psycopg2-binary==2.9.10 trafilatura==2.0.0 werkzeug==3.1.3 wfastcgi==3.0.0

    - name: Run Tests
      run: |
        python -m pytest

    - name: Deploy to Azure
      if: github.ref == 'refs/heads/main'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fastcloseai'
        publish-profile: ${{ secrets.AZUREWEBAPP_PUBLISHPROFILE }}
        package: .