name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Generate requirements.txt
      run: python generate_requirements.py

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      working-directory: ./FastCloseCPA
      run: |
        python -m pytest tests/ -v

    - name: Deploy to Azure
      if: github.ref == 'refs/heads/main'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fastcloseai'
        publish-profile: ${{ secrets.AZUREWEBAPP_PUBLISHPROFILE }}
        package: .
        startup-command: 'gunicorn --bind=0.0.0.0:8000 app:app'