name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        
    - name: Run Tests
      run: |
        python -m pytest
      
    - name: Deploy to Azure
      if: github.ref == 'refs/heads/main'
      env:
        AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZUREWEBAPP_PUBLISHPROFILE }}
      run: |
        python -m pip install azure-cli-core
        az webapp deployment source config-zip --resource-group myResourceGroup --name myApp --src .
